---
- stat:
    path: "{{ homeassistant_directory }}"
  register: dir_stat

- debug:
    var: dir_stat

- shell:
    cmd: "ls -lah /usr/src"
  register: dir_stat

- debug:
    var: dir_stat

- name: Validate components manifests
  shell:
    cmd: /usr/local/bin/python3 -m script.hassfest
    chdir: "{{ homeassistant_directory }}"

- name: Generate Home-Assistant specific PIP requirements
  shell:
    cmd: /usr/local/bin/python3 -m gen_requirements_all
    chdir: "{{ homeassistant_directory }}"

- name: Install Home-Assistant specific PIP requirements
  shell:
    cmd: "/usr/local/bin/python3 -m pip install {{ pip_installation_arguments }} -r requirements_all.txt"
    chdir: "{{ homeassistant_direc tory }}"

- name: Prepare to compile Home-Assistant
  shell:
    cmd: "/usr/local/bin/python3 -m pip install {{ pip_installation_arguments }} -e . \\"
    chdir: "{{ homeassistant_directory }}"

- name: Compile Home-Assistant and dependencies
  shell:
    cmd: "/usr/local/bin/python3 -m compileall homeassistant"
    chdir: "{{ homeassistant_directory }}"
