---

- name: Validate components manifests
  shell:
    cmd: python3 -m script.hassfest
    chdir: "{{ homeassistant_directory }}"

- name: Generate Home-Assistant specific PIP requirements
  shell:
    cmd: python3 -m gen_requirements_all
    chdir: "{{ homeassistant_directory }}"

- name: Install Home-Assistant specific PIP requirements
  shell:
    cmd: "pip3 install {{ pip_installation_arguments }} -r requirements_all.txt"
    chdir: "{{ homeassistant_directory }}"

- name: Prepare to compile Home-Assistant
  shell:
    cmd: "pip3 install {{ pip_installation_arguments }} -e . \"
    chdir: "{{ homeassistant_directory }}"

- name: Compile Home-Assistant and dependencies
  shell:
    cmd: "python3 -m compileall homeassistant"
    chdir: "{{ homeassistant_directory }}"




&& cd /usr/src/homeassistant \
    && python3 -m script.hassfest \
    && python3 -m script.gen_requirements_all \
    && pip3 install --no-cache-dir --no-index --only-binary=:all: --find-links "${WHEELS_LINKS}" \
    -r requirements_all.txt \
    && pip3 install --no-cache-dir --no-index --only-binary=:all: --find-links "${WHEELS_LINKS}" \
    -e . \
    && python3 -m compileall homeassistant