---

- name: Remove any existing configuration directory
  file:
    path: "{{ homeassistant_config_directory }}"
    state: absent

- name: Ensure configuration directory exists
  file:
    path: "{{ homeassistant_config_directory }}"
    state: directory

- name: Ensure custom component directory exists
  file:
    path: "{{ homeaasistant_custom_component_directory }}"
    state: directory

- name: Rendor configuration file to /config
  template:
    src: configuration.yaml.j2
    dest: "{{ homeassistant_config_directory }}/configuration.yaml"

- name: Rendor customization file to /config
  template:
    src: customization.yaml.j2
    dest: "{{ homeassistant_config_directory }}/customization.yaml"
