---

- name: Check out the minimized Home-Assistant repository
  git:
    repo: "{{ minimized_homeassistant_repo }}"
    dest: "{{ homeassistant_directory }}"
    depth: 1

- name: Prepare pip to install directly from VCS repository
  shell:
    cmd: "pip3 install {{ pip_installation_arguments }} -e ./homeassistant"
    chdir: "{{ hitchhiker_working_directory }}"

