---

- name: Upgraade pip
  shell:
    cmd: python3 -m pip install -U pip

- name: Install core pip prerequisites
  pip:
    name: "{{ homeassistant_required_pip_packages }}"
    state: present
    extra_args: "{{ pip_installation_arguments }}"

- name: Install core wheel prerequisites
  pip:
    name: "{{ homeasisitant_required_wheels }}"
    state: present
    extra_args: "{{ pip_find_links_argument }}"
