---

- name: Install core pip prerequisites
  shell:
    cmd: "pip3 install {{ pip_installation_arguments }} {{ item }}"
  loop: "{{ homeassistant_required_pip_packages }}"

- name: Install core pip wheel requirements
  shell:
    cmd: "pip3 install {{ item }} {{ pip_find_links_argument }}"
  loop: "{{ homeaassistant_required_wheel_packages }}"
