---

- name: Install python3-apt
  apt:
    name:
      - python3
      - python3-dev
      - python3-apt
    state: present
    update_cache: yes

- name: Install python apt
  pip:
    name:
      - apt
      - apt_pkg
    state: present

- name: Install required core packages
  apt:
    name: "{{ homeassistant_core_packages }}"
    state: present
    update_cache: yes

- name: Install base component packages
  apt:
    name: "{{ homeassistant_base_component_packages }}"
    state: present
    update_cache: yes

- shell:
    cmd: 'which git'

#- name: Create symbolic link for locale header
#  file:
#    src: /usr/include/locale.h
#    dest: /usr/include/xlocale.h
#    state: link

- name: Disable Avahi Daemon dbus
  replace:
    path: /etc/avahi/avahi-daemon.conf
    regexp: "(#enable-dbus=(?:yes|no))"
    replace: "enable-dbus=no"

- name: Cleanup package cache
  file:
    path: /var/cache/apk/*
    state: absent
