---

- name: Install required core packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ homeassistant_core_packages }}"

- name: Create symbolic link for locale header
  file:
    src: /usr/include/locale.h
    dest: /usr/include/xlocale.h
    state: link

- name: Install base component packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ homeassistant_base_component_packages }}"

- name: Disable Avahi Daemon dbus
  replace:
    path: /etc/avahi/avahi-daemon.conf
    regexp: "(#enable-dbus=(?:yes|no))"
    replace: "enable-dbus=no"

- name: Cleanup package cache
  file:
    path: /var/cache/apk/*
    state: absent
