---

- name: "Check out version {{ component.version }} of the core Home-Assistant repository"
  git:
    repo: "{{ hitchhiker_homeassistant_repo }}"
    depth: 1
    version: "{{ component.version }}"
    dest: /tmp/homeassistant

- name: Save component path and manifest path
  set_fact:
    component_curr_path: "/tmp/homeassistant/homeassistant/components/{{ component.name }}/"
    component_dest_path: "{{ homeassistant_component_directory }}/{{ component.name }}/"
    manifest_path: "{{ homeassistant_component_directory }}/{{ component.name }}/manifest.json"
    component_temp_path: /tmp/homeassistant
  when:
    - '{{ "/tmp/hacs/custom_components/"~component.name is directory }}'

- include_tasks:
    file: components/base




