---

- name: "Check out version {{ component.version }} of HACS repo {{ component.repo }}"
  git:
    repo: "{{ component.repo }}"
    depth: 1
    version: "{{ component.version }}"
    dest: /tmp/hacs

- name: "Locate {{ component.name }} in repo..."
  block:
    - name: "Stat /tmp/hacs/{{ component.name }}"
      stat:
        path: tmp/hacs/{{ component.name }}
      register: top_directory
      ignore_errors: yes

    - name: "Stat /tmp/hacs/custom_components/{{ component.name }}"
      stat:
        path: tmp/hacs/custom_components/{{ component.name }}
      register: second_directory
      ignore_errors: yes

    - name: Save component path and manifest path
      set_fact:
        component_curr_path: "/tmp/hacs/{{ component.name }}/"
        component_dest_path: "{{ homeassistant_component_directory }}/{{ component.name }}/"
        manifest_path: "{{ homeassistant_component_directory }}/{{ component.name }}/manifest.json"
        component_temp_path: /tmp/hacs
      when:
        - top_directory.stat.readable | default(False)

    - name: Save component path and manifest path
      set_fact:
        component_curr_path: "/tmp/hacs/custom_components{{ component.name }}/"
        component_dest_path: "{{ homeassistant_component_directory }}/{{ component.name }}/"
        manifest_path: "{{ homeassistant_component_directory }}/{{ component.name }}/manifest.json"
        component_temp_path: /tmp/hacs
      when:
        - second_directory.stat.readable | default(False)

- include_tasks:
    file: components/base
